server {
  listen 80;
  server_name fenestravie.com www.fenestravie.com;

  root /var/www/custom;
  index index-fenestravie.html;

  location /.well-known {
    alias /var/www/html/fenestravie.com/.well-known;
  }

  location / {
    rewrite ^ https://$host$request_uri? permanent;
  }
}

server {
 listen 443 ssl;

 server_name fenestravie.com www.fenestravie.com;

# ssl_certificate     /etc/letsencrypt/live/fenestravie.com/fullchain.pem;
# ssl_certificate_key /etc/letsencrypt/live/fenestravie.com/privkey.pem;

 ssl_stapling on;
 ssl_stapling_verify on;

  
}
